# Generated by Django 4.0.1 on 2022-03-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_amount_correction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount_correction',
        ),
    ]
