# Generated by Django 4.0.1 on 2022-03-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_amount_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
